/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosterDashboardRouteImport } from './routes/poster.dashboard'
import { Route as PosterCreateRouteImport } from './routes/poster.create'
import { Route as PosterBlogsRouteImport } from './routes/poster.blogs'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminViewersRouteImport } from './routes/admin.viewers'
import { Route as AdminPostersRouteImport } from './routes/admin.posters'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as PosterEditIdRouteImport } from './routes/poster.edit.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterDashboardRoute = PosterDashboardRouteImport.update({
  id: '/poster/dashboard',
  path: '/poster/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterCreateRoute = PosterCreateRouteImport.update({
  id: '/poster/create',
  path: '/poster/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterBlogsRoute = PosterBlogsRouteImport.update({
  id: '/poster/blogs',
  path: '/poster/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewersRoute = AdminViewersRouteImport.update({
  id: '/admin/viewers',
  path: '/admin/viewers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostersRoute = AdminPostersRouteImport.update({
  id: '/admin/posters',
  path: '/admin/posters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterEditIdRoute = PosterEditIdRouteImport.update({
  id: '/poster/edit/$id',
  path: '/poster/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/viewers': typeof AdminViewersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/poster/blogs': typeof PosterBlogsRoute
  '/poster/create': typeof PosterCreateRoute
  '/poster/dashboard': typeof PosterDashboardRoute
  '/poster/edit/$id': typeof PosterEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/viewers': typeof AdminViewersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/poster/blogs': typeof PosterBlogsRoute
  '/poster/create': typeof PosterCreateRoute
  '/poster/dashboard': typeof PosterDashboardRoute
  '/poster/edit/$id': typeof PosterEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posters': typeof AdminPostersRoute
  '/admin/viewers': typeof AdminViewersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/poster/blogs': typeof PosterBlogsRoute
  '/poster/create': typeof PosterCreateRoute
  '/poster/dashboard': typeof PosterDashboardRoute
  '/poster/edit/$id': typeof PosterEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/login'
    | '/profile'
    | '/register'
    | '/unauthorized'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/posters'
    | '/admin/viewers'
    | '/blog/$slug'
    | '/poster/blogs'
    | '/poster/create'
    | '/poster/dashboard'
    | '/poster/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/login'
    | '/profile'
    | '/register'
    | '/unauthorized'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/posters'
    | '/admin/viewers'
    | '/blog/$slug'
    | '/poster/blogs'
    | '/poster/create'
    | '/poster/dashboard'
    | '/poster/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/login'
    | '/profile'
    | '/register'
    | '/unauthorized'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/posters'
    | '/admin/viewers'
    | '/blog/$slug'
    | '/poster/blogs'
    | '/poster/create'
    | '/poster/dashboard'
    | '/poster/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPostersRoute: typeof AdminPostersRoute
  AdminViewersRoute: typeof AdminViewersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PosterBlogsRoute: typeof PosterBlogsRoute
  PosterCreateRoute: typeof PosterCreateRoute
  PosterDashboardRoute: typeof PosterDashboardRoute
  PosterEditIdRoute: typeof PosterEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/dashboard': {
      id: '/poster/dashboard'
      path: '/poster/dashboard'
      fullPath: '/poster/dashboard'
      preLoaderRoute: typeof PosterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/create': {
      id: '/poster/create'
      path: '/poster/create'
      fullPath: '/poster/create'
      preLoaderRoute: typeof PosterCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/blogs': {
      id: '/poster/blogs'
      path: '/poster/blogs'
      fullPath: '/poster/blogs'
      preLoaderRoute: typeof PosterBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/viewers': {
      id: '/admin/viewers'
      path: '/admin/viewers'
      fullPath: '/admin/viewers'
      preLoaderRoute: typeof AdminViewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posters': {
      id: '/admin/posters'
      path: '/admin/posters'
      fullPath: '/admin/posters'
      preLoaderRoute: typeof AdminPostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/edit/$id': {
      id: '/poster/edit/$id'
      path: '/poster/edit/$id'
      fullPath: '/poster/edit/$id'
      preLoaderRoute: typeof PosterEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPostersRoute: AdminPostersRoute,
  AdminViewersRoute: AdminViewersRoute,
  BlogSlugRoute: BlogSlugRoute,
  PosterBlogsRoute: PosterBlogsRoute,
  PosterCreateRoute: PosterCreateRoute,
  PosterDashboardRoute: PosterDashboardRoute,
  PosterEditIdRoute: PosterEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
